project: https://github.com/AudioReach/audioreach-pal

branches:
  qclinux1.0:
    modes:
      blocking:
        headers:
          - inc/PalDefs.h
          - inc/PalApi.h
          - device/inc/Device.h
          - session/inc/Session.h
          - stream/inc/Stream.h
