---
name: pre_merge_build
run-name: Pre Merge Build (PR:${{ github.event.pull_request.number }})

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - qclinux1.0
    paths-ignore:
      - '.github/**'

jobs:
  load_parameters:
    uses: Audioreach/audioreach-workflows/.github/workflows/loading.yml@stg
    with:
      event_name: ${{ github.event_name }}
      pr_ref: ${{ github.event.pull_request.head.ref }}
      pr_repo: ${{ github.event.pull_request.head.repo.full_name }}

  build:
    needs: load_parameters
    uses: Audioreach/audioreach-workflows/.github/workflows/build.yml@stg
    secrets: inherit
    with:
      build_args: ${{ needs.load_parameters.outputs.build_args }}
      event_name: ${{ github.event_name }}
      pr_ref: ${{ github.event.pull_request.head.ref }}
      pr_repo: ${{ github.event.pull_request.head.repo.full_name }}

  process_image:
    needs: [ load_parameters, build ]
    uses: Audioreach/audioreach-workflows/.github/workflows/process_image.yml@stg
    secrets: inherit
    with:
      event_name: ${{ github.event_name }}
      pr_ref: ${{ github.event.pull_request.head.ref }}
      pr_repo: ${{ github.event.pull_request.head.repo.full_name }}

  trigger_lava:
    needs: [ load_parameters, build, process_image ]
    uses: Audioreach/audioreach-workflows/.github/workflows/test.yml@stg
    secrets: inherit

